### ISSUE TITLE
在Ubuntu 18.04上除了HostMonitor外其他示例显示不正常

### ISSUE THREAD

**Issue by wmatrix** [idea4good/GuiLiteSamples#22]
- 编译测试环境：VirtualBox 5.2.10 ,Ubuntu 18.04 64bit GNOME桌面环境
- 示例编译运行：编译构建成功，使用display-x64来运行示例
- 示例测试结果：除了HostMonitor显示正常外，其他示例均显示不正常，具体请看如下截图

HelloAnimation Sample：
![helloanimation](https://user-images.githubusercontent.com/6795531/52832108-1dc2f880-3112-11e9-910a-6b0aff4e0889.png)
HelloFont Sample:
![hellofont](https://user-images.githubusercontent.com/6795531/52832128-2fa49b80-3112-11e9-9a68-abbf42d6dec8.png)
HelloGuiLite Sample:
![helloguilite](https://user-images.githubusercontent.com/6795531/52832135-37fcd680-3112-11e9-85af-b6f087a82959.png)
Hello Particle Sample:
![helloparticle](https://user-images.githubusercontent.com/6795531/52832170-58c52c00-3112-11e9-9117-c471984f753e.png)
HelloSlide Sample:
![helloslide](https://user-images.githubusercontent.com/6795531/52832182-64185780-3112-11e9-8dd2-99f482d25cac.png)
HelloWave Sample:
![hellowave](https://user-images.githubusercontent.com/6795531/52832195-6e3a5600-3112-11e9-9081-515190ae8626.png)
**[OK]HostMonitor Sample:**
![hostmonitor](https://user-images.githubusercontent.com/6795531/52832201-77c3be00-3112-11e9-919d-c59ee046a75b.png)

**Comment by idea4good** [comment]
你给的运行参数不正确
请注意查阅每个示例的readme文件中描述的编译/运行方法

**Comment by wmatrix** [comment]
根据各个示例readme中的运行参数进行运行，示例均运行正常了。我之前只是看到示例的输出来运行的，所以没有添加参数，比如HelloSlide的是如下：

```
-------------------------------------------------------------------
*  GuiLite Sample code [Version 1.6]                              *
*  Any feedback will be appreciated. Email: idea4good@outlook.com *
-------------------------------------------------------------------
How to run inside QT APP?
If x64: ./display-x64 | ./HelloSlide shared-fb
If ARM: ./display-arm | ./HelloSlide shared-fb

How to run on Linux?
Type command: ./HelloSlide /dev/fb-path
```

这里建议在usage输出中加上参数说明会有帮助，类似：
`./display-x64 <shared-id> <width> <height>|./HelloSlide shared-fb`

此外，在运行完一个示例后，如果使用相同的shared-id再次运行另外一个示例，会出现segment fault(core dumped)的错误，这应该是因为共享内存已经创建而且大小不匹配导致的，这个在HelloSlide示例输出中会有提示，但是在其他示例中是没有提示的（出错时），而各个示例的ReadMe文档中的用的shared-id都是1. 

建议是可以在程序退出时可以移除创建的共享内存, 或者是在readme文档或者示例usage输出中加上ipcs相关的说明：

```
          printf("The segment is already there - these segment are persistent - and it has size 2048.\n"
                   "You can see it among the other ones with:\n"
                   "$ ipcs -m\n"
                   "and you can remove your segment (beware: remove your one only) with:\n"
                   "$ ipcrm -M <key>\n"
                   "After that you should be able to create it larger.\n");
```

**Comment by idea4good** [comment]
非常好的意见，非常感谢!
