### ISSUE TITLE
Windows10 + VS2017环境下MFC版本的HostMonitor示例运行出现Assertion failed错误

### ISSUE THREAD

**Issue by wmatrix** [idea4good/GuiLiteSamples#23]
VS2017在Windows10中构建HostMonitor示例，运行后如下图，界面效果不一致，而且鼠标操作时会出现运行时错误：

![hostmonitor-winmfc](https://user-images.githubusercontent.com/6795531/52832428-734bd500-3113-11e9-9d9a-59087c3d00fa.png)

**Comment by idea4good** [comment]
该界面有8个小UI组成（左4右4），拖拽的时候，最好在每个小UI内部完成，不要超过UI边界。
可以双击进行单UI模式，该情况，不会出现拖拽越界的问题。
