### ISSUE TITLE
use uclibc  on arm: fatal error: execinfo.h: No such file or directory

### ISSUE THREAD

**Issue by wmatrix** [idea4good/GuiLiteSamples#25]
使用海思uclibc工具链编译ARM版本的HostMonitor示例时，出现如下错误：
`~/GuiLiteSamples/HostMonitor/BuildLinux/main.cpp:8:22: fatal error: execinfo.h: No such file or directory`

通过注释掉main.cpp文件中的include<execinfo.h>发现可以正常编译通过，可能这个包含不是必须的，建议移除掉。

此外在链接阶段，GCC-4.9.4依然会出现前面提出的issue #24

**Comment by idea4good** [comment]
已经去掉该代码，谢谢你的建议
