### ISSUE TITLE
Mac上编译HostMonitor的时候出现错误

### ISSUE THREAD

**Issue by jiangkang** [idea4good/GuiLiteSamples#27]
错误信息如下：
[ 95%] Built target UIcode
[ 97%] Linking CXX executable HostMonitor
Undefined symbols for architecture x86_64:
  "c_bitmap::draw_bitmap(c_surface*, int, struct_bitmap_info const*, int, int, unsigned int)", referenced from:
      c_bitmap_wave_ctrl::on_paint() in libUIcode.a(wave_ctrl_ex.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [BuildMacCmd/HostMonitor] Error 1
make[1]: *** [BuildMacCmd/CMakeFiles/HostMonitor.dir/all] Error 2
make: *** [all] Error 2

**Comment by idea4good** [comment]
问题已经修改，请更新代码

**Comment by wmatrix** [comment]
在Ubuntu 14.04上编译时也会出现相同的链接错误，不过使用更新的代码问题解决了，链接成功。
