### ISSUE TITLE
HelloGuiLite display unexpected pixels

### ISSUE THREAD

**Issue by zengfanfan** [idea4good/GuiLiteSamples#31]
When I run `BuildLinux/HelloGuiLite /dev/fb0`, it shows:
![image](https://user-images.githubusercontent.com/8079595/70984804-15529a00-20f6-11ea-8e46-2004e605881a.png)

and the command line output:
![image](https://user-images.githubusercontent.com/8079595/70985187-b3defb00-20f6-11ea-93f2-377e586c322d.png)

Why ? Can anyone help?

**system**: CentOS Linux release 7.6.1810 (Core)  (official minimal installation)
**platform**:  VMWare 12.5.2 800M RAM

**Comment by zengfanfan** [comment]
If I set the max resolution of vmware to 640 X 480, then it shows nice (but imcomplete):
![image](https://user-images.githubusercontent.com/8079595/70998802-15ad5e00-2113-11ea-998a-49dbf4495466.png)

The complete nice show is expected to be like this:
[https://github.com/idea4good/GuiLite/raw/master/documents/HelloGuiLite.gif](url)

**Comment by idea4good** [comment]
please run in xWindow mode, you can get more detail in readme file
