### ISSUE TITLE
示例都无法编译通过，都提示 -fPIC 对 cmake 不太了解，我这个要怎么弄

### ISSUE THREAD

**Issue by huye** [idea4good/GuiLiteSamples#5]
这是最后的示提（前面还有很多都是 -fPIC 的）：
`/usr/bin/ld: /home/C/GuiLiteSamples/HostMonitor/BuildLinux/libs/libcore.a(msg_linux.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: 输出不可表示的节
collect2: error: ld returned 1 exit status
CMakeFiles/sample_native.dir/build.make:120: recipe for target 'sample_native' failed
make[2]: *** [sample_native] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sample_native.dir/all' failed
make[1]: *** [CMakeFiles/sample_native.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by idea4good** [comment]
You should run cmake/make in the dir: GuiLiteSamples/HostMonitor

**Comment by idea4good** [comment]
重新编译一下库: libcore.a, libgui.a
