### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by RgznLbq** [idea4good/GuiLiteSamples#9]
建议给GuiLiteSamples写个说明文档，readme说明内容有点少。

**Comment by RgznLbq** [comment]
> readme里面有个“代码走读和注释”，请也看一下。如果仍然觉得内容有点少，应该怎么处理呢？继续在“代码走读和注释”里面补充内容？

GuiLiteSamples 有点复杂。建议对GuiLite增加原理解释实现思路等，还有像HelloGuiLite一样，对每个点做实例这让更容易阅读和理解。

**Comment by idea4good** [comment]
我们又增加了4-5个百行代码的实例程序（包括单片机应用），希望对你有所帮助，谢谢
